[package]
name = "abc001"
version = "0.1.0"
authors = ["eda3 <gerorin1010@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
